<?php
declare(strict_types=1);
require dirname(__DIR__) . '/app/bootstrap.php';
require BASE_PATH . '/app/controllers.php';

$path = strtok($_SERVER['REQUEST_URI'] ?? '/', '?');
$path = '/' . trim(rawurldecode($path), '/');
if ($path === '/') $path = '/';

// Route table: [method, pattern(regex with named groups), handler]
$routes = [
    ['GET',  '#^/$#',                          'home'],
    ['GET',  '#^/explore$#',                   'explore'],
    ['GET',  '#^/in/(?<slug>[a-z0-9\-]+)$#',   'country_show'],
    ['GET',  '#^/discover$#',                  'discover'],
    ['GET',  '#^/d/(?<slug>[a-z0-9\-]+)$#',    'destination'],
    ['GET',  '#^/d/(?<slug>[a-z0-9\-]+)/photos$#', 'destination_photos'],
    ['GET',  '#^/d/(?<slug>[a-z0-9\-]+)/places$#', 'destination_places'],
    ['GET',  '#^/d/(?<slug>[a-z0-9\-]+)/n/(?<nb>[a-z0-9\-]+)$#', 'neighborhood_show'],
    ['GET',  '#^/p/(?<slug>[a-z0-9\-]+)$#',    'place_show'],
    ['POST', '#^/destination/save$#',          'destination_save_action'],
    ['POST', '#^/destination/been$#',          'destination_been_action'],
    ['GET',  '#^/founding$#',                  'founding'],
    ['GET',  '#^/start$#',                     'start_page'],
    ['POST', '#^/place/save$#',                'place_save_action'],
    ['GET',  '#^/saved$#',                     'saved_index'],
    ['GET',  '#^/u/(?<username>[A-Za-z0-9_]+)/edit$#',      'profile_edit_form'],
    ['POST', '#^/u/(?<username>[A-Za-z0-9_]+)/edit$#',      'profile_edit_submit'],
    ['GET',  '#^/u/(?<username>[A-Za-z0-9_]+)/followers$#', 'profile_followers'],
    ['GET',  '#^/u/(?<username>[A-Za-z0-9_]+)/following$#', 'profile_following'],
    ['GET',  '#^/u/(?<username>[A-Za-z0-9_]+)$#','profile'],
    ['GET',  '#^/feed$#',                      'feed'],
    ['GET',  '#^/trip/new$#',                  'trip_new_form'],
    ['POST', '#^/trip/new$#',                  'trip_create'],
    ['GET',  '#^/trip/(?<id>\d+)/edit$#',      'trip_edit_form'],
    ['POST', '#^/trip/(?<id>\d+)/edit$#',      'trip_edit_submit'],
    ['POST', '#^/trip/(?<id>\d+)/delete$#',    'trip_delete'],
    ['GET',  '#^/trip/(?<id>\d+)(?:/[a-z0-9\-]+)?$#', 'trip_show'],
    ['GET',  '#^/reviews$#',                   'reviews_index'],
    ['GET',  '#^/contribute$#',                'contribute_page'],
    ['POST', '#^/event$#',                     'contribution_event'],
    ['POST', '#^/contribute/suggest-place$#',   'contribute_suggest_place'],
    ['GET',  '#^/review/new$#',                'review_new_form'],
    ['POST', '#^/review/new$#',                'review_create'],
    ['GET',  '#^/review/(?<id>\d+)/edit$#',   'review_edit_form'],
    ['POST', '#^/review/(?<id>\d+)/edit$#',   'review_edit_submit'],
    ['POST', '#^/review/(?<id>\d+)/delete$#', 'review_delete'],
    ['POST', '#^/review/(?<id>\d+)/vote$#', 'review_vote_action'],
    ['GET',  '#^/review/(?<id>\d+)(?:/(?<slug>[a-z0-9\-]*))?$#', 'review_show'],
    ['GET',  '#^/guides$#',                    'guides_index'],
    ['GET',  '#^/guide/new$#',                 'guide_new_form'],
    ['POST', '#^/guide/new$#',                 'guide_create'],
    ['GET',  '#^/guide/(?<id>\d+)/edit$#',     'guide_edit_form'],
    ['POST', '#^/guide/(?<id>\d+)/edit$#',     'guide_edit_submit'],
    ['POST', '#^/guide/(?<id>\d+)/delete$#',   'guide_delete'],
    ['GET',  '#^/g/(?<slug>[a-z0-9\-]+)$#',    'guide_show'],
    ['GET',  '#^/blog$#',                      'blog_index'],
    ['GET',  '#^/blog/new$#',                  'blog_new_form'],
    ['POST', '#^/blog/new$#',                  'blog_create'],
    ['GET',  '#^/blog/(?<id>\d+)/edit$#',      'blog_edit_form'],
    ['POST', '#^/blog/(?<id>\d+)/edit$#',      'blog_edit_submit'],
    ['POST', '#^/blog/(?<id>\d+)/delete$#',    'blog_delete'],
    ['GET',  '#^/blog/(?<slug>[a-z0-9\-]+)$#', 'blog_show'],
    ['GET',  '#^/collections$#',                          'collections_index'],
    ['GET',  '#^/collection/new$#',                       'collection_new_form'],
    ['POST', '#^/collection/new$#',                       'collection_create'],
    ['GET',  '#^/collection/(?<id>\d+)/edit$#',           'collection_edit_form'],
    ['POST', '#^/collection/(?<id>\d+)/edit$#',           'collection_edit_submit'],
    ['POST', '#^/collection/(?<id>\d+)/delete$#',         'collection_delete'],
    ['POST', '#^/collection/(?<id>\d+)/items$#',          'collection_item_add'],
    ['POST', '#^/collection/(?<id>\d+)/items/(?<item_id>\d+)/delete$#', 'collection_item_remove'],
    ['GET',  '#^/c/(?<slug>[a-z0-9\-]+)$#',               'collection_show'],
    ['GET',  '#^/meetups$#',                   'meetups_index'],
    ['GET',  '#^/meetup/new$#',                'meetup_new_form'],
    ['POST', '#^/meetup/new$#',                'meetup_create'],
    ['GET',  '#^/meetup/(?<id>\d+)/edit$#',    'meetup_edit_form'],
    ['POST', '#^/meetup/(?<id>\d+)/edit$#',    'meetup_edit_submit'],
    ['POST', '#^/meetup/(?<id>\d+)/cancel$#',  'meetup_cancel'],
    ['GET',  '#^/meetup/(?<id>\d+)$#',         'meetup_show'],
    ['POST', '#^/meetup/(?<id>\d+)/rsvp$#',    'meetup_rsvp'],
    ['GET',  '#^/going$#',                     'going_index'],
    ['POST', '#^/going$#',                     'going_save'],
    ['POST', '#^/going/delete$#',              'going_delete'],
    ['GET',  '#^/travelers$#',                 'travelers_index'],
    ['GET',  '#^/welcome$#',                   'welcome_form'],
    ['POST', '#^/welcome$#',                   'welcome_submit'],
    ['GET',  '#^/leaderboard$#',               'leaderboard'],
    ['GET',  '#^/tags$#',                      'tags_index'],
    ['GET',  '#^/tag/(?<name>[a-z0-9][a-z0-9_\-]{1,29})$#', 'tag_show'],
    ['GET',  '#^/search$#',                    'search'],
    ['GET',  '#^/suggest$#',                   'suggest_json'],
    ['POST', '#^/suggest/click$#',             'suggest_click'],
    ['GET',  '#^/notifications$#',             'notifications'],
    ['GET',  '#^/messages$#',                  'messages_index'],
    ['GET',  '#^/messages/(?<username>[A-Za-z0-9_]+)$#',      'messages_thread'],
    ['POST', '#^/messages/(?<username>[A-Za-z0-9_]+)/send$#','messages_send'],
    ['POST', '#^/block$#',                     'block_action'],
    ['POST', '#^/unblock$#',                   'unblock_action'],
    ['GET',  '#^/unsubscribe$#',                'unsubscribe_action'],
    ['GET',  '#^/settings$#',                  'settings_form'],
    ['POST', '#^/settings$#',                  'settings_save'],
    ['GET',  '#^/login$#',                     'login_form'],
    ['POST', '#^/login$#',                     'login_submit'],
    ['GET',  '#^/register$#',                  'register_form'],
    ['POST', '#^/register$#',                  'register_submit'],
    ['GET',  '#^/logout$#',                    'logout_action'],
    ['GET',  '#^/verify-email$#',              'verify_email'],
    ['POST', '#^/verify-email/confirm$#',      'verify_email_confirm'],
    ['POST', '#^/verify-email/resend$#',       'verify_email_resend'],
    ['GET',  '#^/forgot-password$#',           'forgot_form'],
    ['POST', '#^/forgot-password$#',           'forgot_submit'],
    ['GET',  '#^/reset-password$#',            'reset_form'],
    ['POST', '#^/reset-password$#',            'reset_submit'],
    ['POST', '#^/follow$#',                    'follow_action'],
    ['POST', '#^/compliment$#',                'compliment_action'],
    ['POST', '#^/react$#',                     'react_action'],   // like/save
    ['POST', '#^/comment$#',                   'comment_action'],
    ['POST', '#^/comment/(?<id>\d+)/delete$#', 'comment_delete'],
    ['GET',  '#^/report$#',                    'report_form'],
    ['POST', '#^/report$#',                    'report_submit'],
    ['GET',  '#^/admin$#',                     'admin_dashboard'],
    ['GET',  '#^/admin/places$#',               'admin_places_index'],
    ['GET',  '#^/admin/search$#',               'admin_search_report'],
    ['GET',  '#^/admin/destinations$#',         'admin_destinations_report'],
    ['GET',  '#^/admin/suggestions$#',          'admin_suggestions'],
    ['GET',  '#^/admin/funnel$#',               'admin_funnel'],
    ['GET',  '#^/admin/moderation$#',           'admin_moderation'],
    ['POST', '#^/admin/moderation/act$#',       'admin_moderation_act'],
    ['POST', '#^/admin/suggestions/resolve$#',  'admin_suggestions_resolve'],
    ['GET',  '#^/admin/place/(?<id>\d+)$#',     'admin_place_form'],
    ['POST', '#^/admin/place/(?<id>\d+)$#',     'admin_place_save'],
    ['POST', '#^/admin/place/(?<id>\d+)/photo$#', 'admin_place_photo'],
    ['POST', '#^/admin/resolve$#',             'admin_resolve'],
    ['GET',  '#^/admin/mail-check$#',          'admin_mail_check'],
    ['GET',  '#^/terms$#',                     'page_terms'],
    ['GET',  '#^/privacy$#',                   'page_privacy'],
    ['GET',  '#^/guidelines$#',                'page_guidelines'],
    ['GET',  '#^/affiliate$#',                 'page_affiliate'],
    ['GET',  '#^/safety$#',                    'page_safety'],
    ['GET',  '#^/editorial-policy$#',          'page_editorial'],
    ['GET',  '#^/sitemap\.xml$#',              'sitemap'],
    ['GET',  '#^/feed\.xml$#',                 'feed_rss'],
    ['GET',  '#^/media/(?<key>[a-f0-9]{32}\.(?:jpg|png|webp))$#', 'media_show'],
    ['GET',  '#^/healthz$#',                    'healthz'],
    ['GET',  '#^/readyz$#',                     'readyz'],
];

$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
if ($method === 'HEAD') $method = 'GET'; // serve HEAD via the GET handler (body is discarded by the server)
foreach ($routes as [$m, $rx, $fn]) {
    if ($m !== $method) continue;
    if (preg_match($rx, $path, $params)) {
        $args = array_filter($params, 'is_string', ARRAY_FILTER_USE_KEY);
        $fn($args);
        return;
    }
}
http_response_code(404);
view('404', [], ['title' => 'Not found — RuinMyTrip']);
