-- See 062_post_images.sqlite.sql.
ALTER TABLE posts ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS image_key TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS image_w INTEGER;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS image_h INTEGER;
